# Generated by Django 3.2.12 on 2024-02-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.CharField(default='kaielakara', max_length=64),
            preserve_default=False,
        ),
    ]
