# Generated by Django 3.2.12 on 2024-02-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('AN', 'Anime'), ('CR', 'Cars'), ('NA', 'Nature'), ('SP', 'Self Portrait')], default='Self Portrait', max_length=50),
            preserve_default=False,
        ),
    ]
