# Generated by Django 3.2.12 on 2024-02-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bidder',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
